#!/usr/bin/env bash
#!nstall_load_balancere/usr/bin/env bash
# Installs HAProxy version 2.0 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/hapr
oxy.cfg

printf %s "frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 222-web-01 34.138.163.248:80 check
   server 222-web-02 34.139.154.124:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

systemctl enable haproxy
systemctl start haproxy
