#!/usr/bin/env bash
#simple bash script for protecting database flood > by creating backup by the date name
#echo $1 #test for argument
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf "$(date +"%d-%m-%Y").tar.gz" backup.sql
