#!/usr/bin/env bash
#user pass by argument then check if it exits or not if not create temp user and tell the name
if getent passwd $1 > /dev/null 2>&1; then
sudo -u $1 whoami    
#echo "yes the user exists"
else
   useradd -e `date -d "30 days" +"%Y-%m-%d"` $1
   sudo -u $1 whoami 
#   echo "No, the user does not exist i will creat one for $1"
fi

