#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/error404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
 # Customize HTTP response header
    add_header  X-Served-By 222-web-01;



    location /redirect_me {
        return 301 http://fkadeal.com/;
    

}
  # Serve /airbnb-onepage/ route from AirBnB_clone_v2
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }
   




# Serve
  # Serve /number_odd_or_even/ route on AirBnB_clone_v2
    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
    }






































 error_page 404 /error404.html;

}" > /etc/nginx/sites-available/default

service nginx restart
